version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
        - "dependencies"
        - "java"
  - package-ecosystem: "npm"
    directory: "/frank-flow/src/frontend/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "javascript"
      - "automerge"

