# This dockr compose file is created for the https://flow.frankframework.org demo.
# It runs the container in read-only mode, so it can safely be demoed.
version: "3"

services:
  frank:
    image: frank-flow-demo
    build: .
    read_only: true
    tmpfs:
      - /usr/local/tomcat/logs
      - /usr/local/tomcat/conf/Catalina
      - /usr/local/tomcat/work/Catalina/localhost
      - /usr/local/tomcat/temp
    ports:
      - "85:8080"
    restart: unless-stopped
