name: Run Cypress test
on: push
jobs:
  cypress-test:
    runs-on: windows-latest
    steps:
      - name: Checkout this frank-flow repository
        uses: actions/checkout@v2
        with:
          path: frank-flow
      - name: Setup Node
        uses: actions/setup-node@v2
      - name: Checkout frank-runner
        uses: actions/checkout@v2
        with:
          repository: ibissource/frank-runner
          path: frank-runner
      - name: Build backend
        run: mvn -f frank-flow -P frontend --log-file backendMavenBuildLog.txt clean install          
      - name: List all files
        run: tree > allFiles.txt
      - name: Store file listing artifact
        uses: actions/upload-artifact@v2
        with:
          name: allFiles.txt
          path: allFiles.txt
      - name: Store Maven build output
        uses: actions/upload-artifact@v2
        with:
          name: backendMavenBuildLog.txt
          path: backendMavenBuildLog.txt
