name: Run Cypress test
on: push
jobs:
  cypress-test:
    runs-on: windows-latest
    steps:
      - name: Checkout this frank-flow repository
        uses: actions/checkout@v2
        with:
          path: frank-flow
      - name: Setup Node
        uses: actions/setup-node@v2
      - name: Checkout frank-runner
        uses: actions/checkout@v2
        with:
          repository: ibissource/frank-runner
          path: frank-runner
      - name: Write frank-flow.properties
        run: echo "frank-flow.frontend-path = ${pwd}\\frank-flow\\src\\frontend" > frank-runner\\frank-flow.properties
      - name: Build backend
        run: mvn -f frank-flow -P frontend --log-file backendMavenBuildLog.txt clean install          
      - name: List all files
        run: tree > allFiles.txt
      - name: Run cypress test
        uses: cypress.io/github-action@v2.9.7
        with:
          service: ant -buildfile frank-flow\\frank-flow\\src\\frontend\\cypress\\Frank
          start: cd frank-flow\src\frontend; npx cypress run
      - name: Store (logging) information as artifact
        uses: actions/upload-artifact@v2
        with:
          name: logs
          path: |
            allFiles.txt
            backendMavenBuildLog.txt
            frank-runner\\build.properties
            frank-runner\\frank-flow.properties
