name: End to End Testing (Frank!Runner)

on:
  workflow_dispatch:

jobs:
  e2e-frank-runner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout frank-flow repository
        uses: actions/checkout@v2
        with:
          path: frank-flow
      - name: Checkout frank-runner repository
        uses: actions/checkout@v2
        with:
          repository: ibissource/frank-runner
          path: frank-runner
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Write frank-flow.properties
        run: echo "frank-flow.frontend-path = $(pwd)/frank-flow/frank-flow/target/frontend" > frank-runner/frank-flow.properties
      - name: Build the backend
        working-directory: frank-flow
        run: mvn install
      - name: Cache local Maven repository
        uses: actions/cache@v2
        env:
          cache-name: cache-maven-dependencies
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Cache frank-runner dependencies
        uses: actions/cache@v2
        with:
          path: |
            frank-runner/build
            frank-runner/download
          key: ${{ runner.os }}-frank-runner
          restore-keys: |
            ${{ runner.os }}-frank-runner
      - name: Run Cypress using the frank-runner
        uses: cypress-io/github-action@v2.9.7
        with:
          working-directory: frank-flow/frank-flow/src/frontend/
          build: yarn build
          start: yarn runner
          wait-on: "http://localhost:8080/frank-flow/"
          wait-on-timeout: 360
      - name: Store (logging) information as artifacts
        uses: actions/upload-artifact@v2
        with:
          name: logs
          path: |
            frank-runner/build/apache-tomcat-9.0.50/logs/catalina.out
