name: Semantic Release

on:
  workflow_run:
    branches: [ "master" ]
    workflows: [ "Frontend CI" ]
    types:
      - completed

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout frank-flow repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: true
          path: frank-flow
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Install dependencies
        run: yarn global add semantic-release @semantic-release/changelog @semantic-release/git @semantic-release/exec conventional-changelog-metahub

      - name: Run semantic release
        working-directory: frank-flow
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: chmod +x ./prepare-release.sh && semantic-release

      - name: Make snapshot version
        working-directory: frank-flow
        run: chmod +x ./prepare-snapshot.sh && ./prepare-snapshot.sh

      - name: Commit pom changes
        uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
        with:
          add: '**/pom.xml'
          cwd: 'frank-flow'
          github_token: ${{ secrets.GH_TOKEN }}
          default_author: github_actor
          author_name: Sergi Philipsen
          author_email: philipsen.sergi@gmail.com
          committer_name: GitHub Actions
          committer_email: actions@github.com
          message: 'chore(release): create new snapshot version [skip ci]'