name: Snapshot

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout frank-flow repository
        uses: actions/checkout@v2

      - name: Run snapshot script
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: chmod +x ./prepare-snapshot.sh && ./prepare-snapshot.sh

      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: commit
        run: |
          git add **/pom.xml
          git commit -m "chore(release): prepare snapshot [skip ci]"
          git push origin master --no-verify